[package]
name = "runjs"
version = "0.1.0"
edition = "2021"
publish = ["gitea"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.272.0"
tokio = { version = "1.37.0", features = ["full"] }
