[package]
name = "runjs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_ast = {version = "0.35.0", features = ["transpiling"]}
deno_core = "0.272.0"
reqwest = "0.12.2"
tokio = { version = "1.37.0", features = ["full"] }
